# docker-compose.yml

version: '3.7'

services:
  web:
    build: ./
    command: yarn go
    volumes:
      - '.:/app'
      - 'node_modules:/app/node_modules'
    ports:
      - 4567:4567
    env_file:
      - .env

volumes:
  node_modules:
